### PR TITLE
Added an icon

### PR DESCRIPTION
**Pull request by gaurav-nelson**
Based on https://code.visualstudio.com/api/references/extension-manifest

Added an icon with:
- AsciiDoc logo
- Contrasting colors that look good on both dark and light backgrounds

Hopefully better than the default one. 🥂

### CODE REVIEW

**Comment by gaurav-nelson** [comment]
@apupier @abhatt-rh Can this PR get some ❤️

**Review by apupier — APPROVED** [review]
- Asciidoctor logo https://github.com/asciidoctor/asciidoctor-docs-ui/blob/main/src/img/asciidoctor-logo.svg is in a repo with [Mozilla Public License](https://github.com/asciidoctor/asciidoctor-docs-ui/blob/main/LICENSE). Not very familiar with it but sounds we can reuse it.

**Comment by abhatt-rh** [comment]
@gaurav-nelson Sorry about the delay; that was my bad! Merged now

**Comment by gaurav-nelson** [comment]
Thank you 🌟 I'm not sure how frequently do you update the extension, but you'll need to make a new release for this logo to appear in the marketplace and elsewhere.

Thank you again for merging this PR. 🥂

**Comment by abhatt-rh** [comment]
> Thank you star2 I'm not sure how frequently do you update the extension, but you'll need to make a new release for this logo to appear in the marketplace and elsewhere.
> 
> Thank you again for merging this PR. clinking_glasses

Hi @gaurav-nelson I have a couple of updates which are in progress. I was thinking of finishing up with them and then make a new release (tentatively by end of Oct), which would include your submission too. Thank you again for the cool icon :)

**Comment by gaurav-nelson** [comment]
@abhatt-rh Any updates on publishing a new version to the Marketplace?

**Comment by abhatt-rh** [comment]
> @abhatt-rh Any updates on publishing a new version to the Marketplace?

Sincere apologies for the delayed reply. I was not able to get to this sooner but @apupier published a new released and that included the super cool icon. Thank you @gaurav-nelson and @apupier

**Pull request merged**
